import type { Application, Candidate, CompanyProfile, CvSection, Job, SeekerProfile } from "./types";

export const SKILL_LIBRARY = [
  "SQL",
  "Excel",
  "Python",
  "Power BI",
  "Tableau",
  "Data Visualization",
  "Statistics",
  "Machine Learning",
  "Deep Learning",
  "Pandas",
  "NLP",
  "Java",
  "React",
  "TypeScript",
  "Node.js",
  "Figma",
  "UX Research",
  "Cloud (AWS)",
  "Docker",
  "Communication",
  "Problem Solving",
  "Project Management",
];

export const defaultSeeker: SeekerProfile = {
  fullName: "Sarah Ahmed",
  email: "sarah.ahmed@example.com",
  phone: "+966 50 123 4567",
  title: "Computer Science Graduate",
  degree: "Bachelor's degree",
  major: "Computer Science",
  university: "King Saud University",
  gpa: "4.4 / 5.0",
  graduationYear: 2025,
  location: "Riyadh, Saudi Arabia",
  years: 1,
  skills: ["SQL", "Excel", "Python", "Pandas", "Statistics", "Communication", "Problem Solving"],
  certifications: ["Google Data Analytics"],
  languages: ["Arabic (Native)", "English (Fluent)"],
};

export const defaultCv = (p: SeekerProfile): CvSection => ({
  personal: {
    fullName: p.fullName,
    title: "Data Analyst",
    email: p.email,
    phone: p.phone,
    location: p.location,
    summary:
      "Computer Science graduate with hands-on experience turning raw data into clear decisions. Strong in SQL and Python, with a track record of building dashboards and analytical reports for real stakeholders.",
  },
  education: [
    {
      degree: `${p.degree} in ${p.major}`,
      school: p.university,
      period: `2021 — ${p.graduationYear}`,
      gpa: p.gpa,
    },
  ],
  skills: p.skills,
  experience: [
    {
      role: "Data Analysis Intern",
      company: "stc",
      period: "Jun 2024 — Sep 2024",
      summary:
        "Built SQL reporting queries and Excel dashboards for the customer insights team, reducing weekly reporting time by 40%.",
    },
  ],
  projects: [
    {
      name: "Retail Sales Insights Dashboard",
      description:
        "Analysed 120k sales records with Python and Pandas and presented findings in an interactive dashboard.",
    },
  ],
  certifications: p.certifications,
  languages: p.languages,
});

export const defaultCompany: CompanyProfile = {
  name: "Tech Company",
  industry: "Information Technology",
  size: "201 — 500 employees",
  website: "https://techcompany.sa",
  location: "Riyadh, Saudi Arabia",
  description:
    "We build data and cloud products for enterprises across the Gulf. Our teams work on analytics platforms, AI services and secure infrastructure.",
  team: [
    { name: "Noura Al Harbi", role: "HR Manager", email: "noura@techcompany.sa" },
    { name: "Faisal Otaibi", role: "Talent Partner", email: "faisal@techcompany.sa" },
  ],
};

export const JOBS: Job[] = [
  {
    id: "job-data-analyst",
    title: "Data Analyst",
    company: "stc",
    companyLogo: "stc",
    location: "Riyadh, Saudi Arabia",
    type: "Full-time",
    level: "Entry level",
    salary: "SAR 9,000 — 12,000 / month",
    posted: "2 days ago",
    description:
      "Join the customer insights team to turn operational data into decisions. You will build reports, maintain dashboards and work closely with business owners across the company.",
    responsibilities: [
      "Write and optimise SQL queries against the data warehouse",
      "Build and maintain Power BI dashboards for business teams",
      "Present weekly insight summaries to stakeholders",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, Statistics or related field",
      "0 — 2 years of experience in an analytical role",
      "Comfortable presenting findings to non-technical audiences",
    ],
    skills: ["SQL", "Excel", "Power BI", "Data Visualization"],
    preferredSkills: ["Python", "Statistics"],
    education: "Bachelor's degree",
    minYears: 0,
    certifications: ["Google Data Analytics"],
    status: "Active",
    applicants: 120,
    shortlisted: 14,
    interviews: 6,
    hired: 1,
  },
  {
    id: "job-ai-engineer",
    title: "AI Engineer",
    company: "Aramco Digital",
    companyLogo: "AD",
    location: "Dhahran, Saudi Arabia",
    type: "Full-time",
    level: "Mid level",
    salary: "SAR 16,000 — 22,000 / month",
    posted: "5 days ago",
    description:
      "Design and ship machine learning services that support industrial operations, from data pipelines through to deployed models.",
    responsibilities: [
      "Develop and evaluate ML models for forecasting and anomaly detection",
      "Package models as production services",
      "Partner with data engineers on feature pipelines",
    ],
    requirements: [
      "Bachelor's degree in Computer Science or AI",
      "2+ years building machine learning systems",
      "Strong Python engineering fundamentals",
    ],
    skills: ["Python", "Machine Learning", "Deep Learning", "Docker"],
    preferredSkills: ["Cloud (AWS)", "NLP"],
    education: "Bachelor's degree",
    minYears: 2,
    certifications: ["AWS Machine Learning Specialty"],
    status: "Active",
    applicants: 48,
    shortlisted: 9,
    interviews: 3,
    hired: 0,
  },
  {
    id: "job-bi-analyst",
    title: "Business Intelligence Analyst",
    company: "Almarai",
    companyLogo: "AL",
    location: "Riyadh, Saudi Arabia",
    type: "Full-time",
    level: "Entry level",
    salary: "SAR 8,500 — 11,000 / month",
    posted: "1 week ago",
    description:
      "Support commercial teams with reporting, forecasting and self-service analytics across the supply chain.",
    responsibilities: [
      "Model data for reporting layers",
      "Automate recurring reports",
      "Train business users on dashboards",
    ],
    requirements: ["Bachelor's degree", "Strong Excel and SQL", "Detail oriented"],
    skills: ["SQL", "Excel", "Power BI"],
    preferredSkills: ["Tableau", "Communication"],
    education: "Bachelor's degree",
    minYears: 0,
    certifications: [],
    status: "Active",
    applicants: 76,
    shortlisted: 11,
    interviews: 4,
    hired: 0,
  },
  {
    id: "job-junior-data-scientist",
    title: "Junior Data Scientist",
    company: "Jahez",
    companyLogo: "JZ",
    location: "Remote — Saudi Arabia",
    type: "Remote",
    level: "Entry level",
    salary: "SAR 11,000 — 14,000 / month",
    posted: "3 days ago",
    description:
      "Work with product and growth teams to run experiments, build predictive models and measure impact.",
    responsibilities: [
      "Run A/B tests and analyse results",
      "Build baseline predictive models",
      "Communicate findings to product managers",
    ],
    requirements: ["Bachelor's degree", "Python and statistics", "Curiosity about product metrics"],
    skills: ["Python", "Statistics", "SQL", "Machine Learning"],
    preferredSkills: ["Pandas", "Data Visualization"],
    education: "Bachelor's degree",
    minYears: 1,
    certifications: [],
    status: "Active",
    applicants: 92,
    shortlisted: 7,
    interviews: 2,
    hired: 0,
  },
  {
    id: "job-frontend",
    title: "Frontend Engineer",
    company: "Tamara",
    companyLogo: "TM",
    location: "Riyadh, Saudi Arabia",
    type: "Full-time",
    level: "Mid level",
    salary: "SAR 15,000 — 19,000 / month",
    posted: "1 day ago",
    description:
      "Build delightful, accessible checkout and merchant experiences used by millions of shoppers.",
    responsibilities: [
      "Ship features in React and TypeScript",
      "Own component quality and accessibility",
      "Collaborate closely with design",
    ],
    requirements: ["Bachelor's degree", "2+ years with React", "Strong CSS fundamentals"],
    skills: ["React", "TypeScript", "Node.js"],
    preferredSkills: ["Figma", "Communication"],
    education: "Bachelor's degree",
    minYears: 2,
    certifications: [],
    status: "Active",
    applicants: 64,
    shortlisted: 8,
    interviews: 3,
    hired: 0,
  },
  {
    id: "job-product-analyst",
    title: "Product Analyst — Internship",
    company: "Nana",
    companyLogo: "NA",
    location: "Riyadh, Saudi Arabia",
    type: "Internship",
    level: "Entry level",
    salary: "SAR 4,000 / month",
    posted: "4 days ago",
    description:
      "A six-month internship for students and fresh graduates who want to learn product analytics in a fast-moving team.",
    responsibilities: [
      "Prepare weekly product metrics",
      "Support experiment analysis",
      "Document findings",
    ],
    requirements: ["Final year student or fresh graduate", "Excel and basic SQL"],
    skills: ["Excel", "SQL", "Communication"],
    preferredSkills: ["Data Visualization"],
    education: "Bachelor's degree",
    minYears: 0,
    certifications: [],
    status: "Active",
    applicants: 140,
    shortlisted: 20,
    interviews: 8,
    hired: 2,
  },
];

export const CANDIDATES: Candidate[] = [
  {
    id: "cand-sara",
    name: "Sara Ahmed",
    initials: "SA",
    title: "Data Analyst",
    degree: "Bachelor's degree",
    major: "Computer Science",
    university: "King Saud University",
    gpa: "4.6 / 5.0",
    graduationYear: 2025,
    location: "Riyadh, Saudi Arabia",
    availability: "Immediately",
    years: 1,
    skills: ["SQL", "Python", "Power BI", "Excel", "Data Visualization", "Statistics"],
    certifications: ["Google Data Analytics"],
    languages: ["Arabic (Native)", "English (Fluent)"],
    projects: [
      {
        name: "Retail sales dashboard",
        description: "Power BI dashboard over 120k rows of retail transactions.",
      },
    ],
    experience: [
      {
        role: "Data Analysis Intern",
        company: "stc",
        period: "2024",
        summary: "Reporting automation and SQL modelling for customer insights.",
      },
    ],
    summary: "Fresh graduate with a strong analytics portfolio and real internship delivery.",
  },
  {
    id: "cand-omar",
    name: "Omar Alharbi",
    initials: "OA",
    title: "Information Systems Graduate",
    degree: "Bachelor's degree",
    major: "Information Systems",
    university: "King Fahd University",
    gpa: "4.1 / 5.0",
    graduationYear: 2024,
    location: "Dhahran, Saudi Arabia",
    availability: "1 month",
    years: 2,
    skills: ["SQL", "Power BI", "Excel", "Project Management"],
    certifications: ["Microsoft PL-300"],
    languages: ["Arabic (Native)", "English (Advanced)"],
    projects: [
      { name: "Supply chain KPIs", description: "Automated KPI reporting for a logistics team." },
    ],
    experience: [
      {
        role: "BI Analyst",
        company: "Almarai",
        period: "2023 — 2025",
        summary: "Owned commercial dashboards and data quality checks.",
      },
    ],
    summary: "Two years of BI delivery in a large enterprise environment.",
  },
  {
    id: "cand-lina",
    name: "Lina Abdullah",
    initials: "LA",
    title: "Software Engineer",
    degree: "Bachelor's degree",
    major: "Software Engineering",
    university: "Princess Nourah University",
    gpa: "4.8 / 5.0",
    graduationYear: 2025,
    location: "Riyadh, Saudi Arabia",
    availability: "Immediately",
    years: 1,
    skills: ["Java", "Python", "Machine Learning", "SQL", "Docker"],
    certifications: ["AWS Cloud Practitioner"],
    languages: ["Arabic (Native)", "English (Fluent)"],
    projects: [
      {
        name: "Arabic sentiment model",
        description: "NLP classifier for Arabic customer reviews with 88% accuracy.",
      },
    ],
    experience: [
      {
        role: "ML Intern",
        company: "Elm",
        period: "2024",
        summary: "Model evaluation and data labelling pipelines.",
      },
    ],
    summary: "Top-of-class engineer moving toward applied machine learning.",
  },
  {
    id: "cand-khalid",
    name: "Khalid Alzahrani",
    initials: "KA",
    title: "Data Scientist",
    degree: "Master's degree",
    major: "Data Science",
    university: "KAUST",
    gpa: "3.9 / 4.0",
    graduationYear: 2023,
    location: "Jeddah, Saudi Arabia",
    availability: "3 months",
    years: 3,
    skills: ["Python", "Machine Learning", "Deep Learning", "NLP", "Cloud (AWS)", "Docker"],
    certifications: ["AWS Machine Learning Specialty"],
    languages: ["Arabic (Native)", "English (Fluent)"],
    projects: [
      {
        name: "Demand forecasting",
        description: "Forecasting service reducing stock-outs by 18%.",
      },
    ],
    experience: [
      {
        role: "Data Scientist",
        company: "Aramco Digital",
        period: "2023 — 2026",
        summary: "Production ML for industrial operations.",
      },
    ],
    summary: "Experienced applied scientist with production deployment track record.",
  },
  {
    id: "cand-noura",
    name: "Noura Saeed",
    initials: "NS",
    title: "Frontend Engineer",
    degree: "Bachelor's degree",
    major: "Computer Science",
    university: "King Abdulaziz University",
    gpa: "4.3 / 5.0",
    graduationYear: 2024,
    location: "Riyadh, Saudi Arabia",
    availability: "1 month",
    years: 2,
    skills: ["React", "TypeScript", "Node.js", "Figma", "Communication"],
    certifications: [],
    languages: ["Arabic (Native)", "English (Fluent)"],
    projects: [
      { name: "Design system", description: "Built a shared component library used by 4 teams." },
    ],
    experience: [
      {
        role: "Frontend Engineer",
        company: "Tamara",
        period: "2024 — 2026",
        summary: "Checkout experience and accessibility improvements.",
      },
    ],
    summary: "Product-minded frontend engineer with design system ownership.",
  },
  {
    id: "cand-rayed",
    name: "Rayed Bandar",
    initials: "RB",
    title: "Product Analyst",
    degree: "Bachelor's degree",
    major: "Statistics",
    university: "Imam University",
    gpa: "3.8 / 5.0",
    graduationYear: 2026,
    location: "Riyadh, Saudi Arabia",
    availability: "Immediately",
    years: 0,
    skills: ["Excel", "SQL", "Statistics", "Communication"],
    certifications: [],
    languages: ["Arabic (Native)", "English (Intermediate)"],
    projects: [
      { name: "Campus survey study", description: "Survey design and analysis for 1,200 students." },
    ],
    experience: [],
    summary: "Final year statistics student looking for a first analytics role.",
  },
];

export const SEED_APPLICATIONS: Application[] = [
  {
    id: "app-1",
    jobId: "job-bi-analyst",
    status: "Under Review",
    appliedAt: "3 days ago",
    timeline: [
      { label: "Application submitted", date: "3 days ago", done: true },
      { label: "CV screened by AI", date: "2 days ago", done: true },
      { label: "Under review by hiring team", date: "Today", done: true },
      { label: "Interview", date: "Pending", done: false },
    ],
  },
  {
    id: "app-2",
    jobId: "job-product-analyst",
    status: "Shortlisted",
    appliedAt: "1 week ago",
    timeline: [
      { label: "Application submitted", date: "1 week ago", done: true },
      { label: "CV screened by AI", date: "6 days ago", done: true },
      { label: "Shortlisted", date: "2 days ago", done: true },
      { label: "Interview", date: "Pending", done: false },
    ],
  },
  {
    id: "app-3",
    jobId: "job-frontend",
    status: "Rejected",
    appliedAt: "2 weeks ago",
    timeline: [
      { label: "Application submitted", date: "2 weeks ago", done: true },
      { label: "CV screened by AI", date: "13 days ago", done: true },
      { label: "Not selected", date: "9 days ago", done: true },
    ],
  },
];

export const CV_TEMPLATES = [
  { id: "classic", name: "Classic", description: "Clean single column, ATS friendly." },
  { id: "modern", name: "Modern", description: "Teal accents with a skills sidebar." },
  { id: "compact", name: "Compact", description: "Fits more detail on one page." },
];

export function jobById(id: string) {
  return JOBS.find((j) => j.id === id);
}

export function candidateById(id: string) {
  return CANDIDATES.find((c) => c.id === id);
}

export const defaultCvFor = defaultCv;
